### ISSUE TITLE
Create initial snakemake workflow for ANIm

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#2]
We need an example (realistic) snakemake workflow for ANIm (using `nucmer`) to generate the appropriate output files.

As we intend the new pyani to be modular, we should organise the codebase to reflect this (module names/directory names/filenames)

Ultimately, we'll be looking to have a set of modular workflows for different kinds of whole-genome analysis (ANIm/ANIb/fastANI/etc.) - all called from pyani.

**Comment by kiepczi** [comment]
I have been working on this under the branch `issue_1`. I didn't want to start too many branches since issues 1 to 4 are related and follow from each other.

The workflow has been provided with the [41d716b](https://github.com/pyani-plus/pyani-plus/commit/41d716bbdbbbbe08b90003ff0d678b38b3f6f83e) commit.

I have been building on the example code written by @widdowquinn, which can be found [here](https://pyani-plus.github.io/design-documentation/snakemake.html).

The main differences are that the current workflow/script provided in `run_anim_workflow.py` will:

- Generate `delta-filter` files instead of `nucmer` (`delta`) files. This change is because we will need/use `.filter` files for all ANIm calculations rather than `delta` files only. The `Snakemake` workflow is designed so that `nucmer` will always be called first to obtain `delta` files, which are then used as an input to call `delta-filter`. However, this part of the code will need testing to ensure everything is working as intended.
- Instead of passing a list of target `filter` files, I have written a function called `get_target_files` to generate target files (both forward and reverse) for a given set of input files. This portion of the code has been tested with `pytest` [here](https://github.com/pyani-plus/pyani-plus/blob/issue_1/tests/test_snakemake_anim_workflow.py).
