### ISSUE TITLE
Need New Viral Genome Set for ANI Testing

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#94]
We talked about using the values reported by `pyani v3` as the ground truth after fixing the genome coverage issue. However, the current set of viral genomes (comprising 4 genomes) is too diverse, resulting in a `ZeroDivisionError`. 

To ensure that multi-way comparisons are generated and that we can validate the ANI values against those returned by `pyani v3`, we need a set of viral genomes consisting of at least four genomes, with at least a portion of each genome aligning.

Additionally, it would be beneficial to obtain another set of genomes that will not align. This will help us test the handling of the `ZeroDivisionError` to ensure it correctly returns zero when applicable.

**Comment by peterjc** [comment]
The four viruses were added in #87, I started with the two from the initial issue report, expanded as discussed (Leighton wanted to have 3 or 4). As far as I could see there were only 2 more on the issue - were any other examples being shared? If so we can tweak which are used.

However, I think the divide-by-zero error is actually a good thing - we talked yesterday about needing test cases with very very bad alignments and how depending on the circumstances a zero of NaN (not a number) might be sensible. It turns out I set one up unintentionally lol🤣

For the specifics of testing a given ANI value, we don't need to do an all-vs-all. You could do a pairwise comparison of any two of the bacteria for example, ground truthed with the pyani v3 output?

**Comment by kiepczi** [comment]
I have found more genomes, where there is no `ZeroDevisionError`. I will be committing new set soon.

**Comment by peterjc** [comment]
Handled via #98
